### ISSUE TITLE
Potential Conflict

### ISSUE THREAD

**Issue by NanhuGITHUB** [brendanv/calm-new-tab#1]
This may have a Conflict with [Calm New Tab](https://calm-dash.com/) (not Open Source)

**Comment by brendanv** [comment]
Thanks for the heads up, I hadn't heard of that extension before! I assume you mean a conflict about naming? Since this is mostly a hobby project, I'll leave the name as-is for now but I'm happy to change it if they reach out to me. 

As for this project having many of the same features as other new tab extensions, that's by design. There are a bunch of new tab extensions with similar features but when I built this I wanted a trimmed down version that just does one thing. I didn't need weather, or a todo list, or a search bar that's worse than chrome's omnibar. I also liked the idea of making it open source.

Thanks again for the report!

**Comment by NanhuGITHUB** [comment]
OK

**Comment by NanhuGITHUB** [comment]
and Yes, Naming Conflict
